services:

  aptp:

    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: aptp

    restart: unless-stopped

    network_mode: host

    privileged: true

    volumes:

      - ../backend:/app/backend
      - ../frontend:/app/frontend
      - ../data:/app/data
      - /etc/hostname:/etc/host_hostname:ro
      - /etc/NetworkManager:/etc/NetworkManager
      - /run/NetworkManager:/run/NetworkManager
      - /var/run/dbus:/var/run/dbus

    environment:
      - FLASK_ENV=development

    command: >
      flask
      --app backend.app
      run
      --host=0.0.0.0
      --port=8080
      --debug